version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=senha_root
      - DB_NAME=endpoint-do-banco
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=senha_root
      - MYSQL_DATABASE=nome_do_banco
    ports:
      - "3306:3306"